```plantuml
@startmindmap
* 🐟 Потенциальные узкие места при миграции
** Инфраструктура
*** Один физический сервер без отказоустойчивости
*** Локальное размещение, нет облака
*** Нехватка ресурсов при масштабировании
** Программное обеспечение
*** Excel и 1С в файловом режиме
*** Нет CI/CD, автотестов
*** Ручной деплой и обновления
** Интеграции
*** Отсутствие API в старых системах
*** Проблемы миграции Excel и PDF
*** Невозможность валидации схем
** Персонал
*** IT-отдел перегружен
*** Нет DevOps и архитектора
*** Отсутствие опыта в микросервисах и Kubernetes
** Процессы
*** Отсутствие стратегии миграции
*** Нет тестовой среды
*** Сложность ведения двух систем параллельно
** Безопасность
*** Данные не зашифрованы
*** Нет централизованного контроля доступа
*** Нет SIEM, DLP и IAM
@endmindmap